dist: trusty
sudo: false
language: python
python:
- '3.5'
jdk:
- oraclejdk8
addons:
  sonarqube:
    organization: gabriellmb05-github
    token:
      secure: "$SONAR_TOKEN"
branches:
  only:
  - master
install:
- pip install -r requirements.txt
script:
- sonar-scanner -Dsonar.login=$SONAR_TOKEN
deploy:
  provider: heroku
  api_key:
    secure: JfJC2QawbpTQIEeIRsSqDR/HWGYldwrzVgVysqFaKVV4R+N4ZtyuPqSd1wL5fBsecYtMWaC+7FnJ2VDVd4iV0hg5R5JjYakOsNVDFZ17j/ucLCxhYOe535SJMfThwUtqVJ9NxDyJw+0YTekDCBPvfWucdGIbRPY/1HSrqCvdbouUBredPNQOwl1518Gs9791AYxswyVYmfjrfq/GL1N6kM3saI5nlPnMHqmTpx8BgR2jiQay4gprK/clfAyXmVBBz4cYNISbLvaUkIRGtensanGiSZdyptwZYSK2oLtCj2F6vasJSG74T1enOLKRG1h2br3/c3RVrnv0Lp/Op1w97N7RH8IZitg+M2tlSIu82THYhTkY7EvK9koPRhNCnBCmTNqVHyOVv5Fiwyv600LKfhmFUuoHhW4LQt3seVsZR5tuu3zZJhHhmsqBZI5P7scYnlbm2yHXcG+B+YeVWJTPR+m0gKhfcOKJ7QZ8/nlHYJEm4zYjf815Mn0TExyEdSLT8xh23yDlWPBB436mcKWiAkEPzKOOeQaazqTRByku88UWsHSROurshyL9xsY+e5ZHgGl931Sb2H+NsZbhONlNLDSJOTA1sVeMJG776OZGCEi9s+h8miQpj+1Yl6OOCALBmm39HTVhS41vWJ2ANO9l/bsz3fdVY0WmPEyFug+5EfQ=
  app: trabalho-lesw
  on:
    repo: gabriellmb05/trabalho-les
