# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credencial',
            name='token',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
