# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0003_auto_20170427_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credencial',
            name='token',
            field=models.CharField(blank=True, max_length=60, unique=True),
        ),
    ]
